Repository FISCO-BCOS/java-sdk, pull requests merged in 2022-03, with the labels that each got.

#486 add enableDAG setter/getter to contract
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/contract/Contract.java
Labels: 3.0.0-rc3, dag

#501 sync code from release-3.0.0-rc2-bugfix
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/ABICodec.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/abi/TypeEncoder.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/datatypes/Array.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/datatypes/DynamicArray.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/scale/TypeDecoder.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABICodecJsonWrapper.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABICodecObject.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABIObject.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABIObjectFactory.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/ABICodecTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/abi/ContractTypeTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/abi/TableTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/wrapper/ABIObjectCodecTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/wrapper/ABIObjectTest.java
  sdk-core/src/main/java/org/fisco/bcos/sdk/model/PrecompiledRetCode.java
  sdk-service/src/test/java/org/fisco/bcos/sdk/test/precompiled/PrecompiledRetCodeTest.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/codec/decode/TransactionDecoderService.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessor.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessorInterface.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionWithRemoteSignProcessor.java
  src/integration-test/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessorTest.java
Labels: v3.x, sync-code

#500 <refactor>(codec): ABICodec refactor to ContractCodec.
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/ContractCodec.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/ContractCodecException.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABIObject.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ABIObjectFactory.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ContractCodecJsonWrapper.java
  sdk-codec/src/main/java/org/fisco/bcos/sdk/codec/wrapper/ContractCodecTools.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/ABICodecTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/abi/ABIEventTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/abi/ContractTypeTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/abi/TableTest.java
  sdk-codec/src/test/java/org/fisco/bcos/sdk/codec/wrapper/ABIObjectCodecTest.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/contract/Contract.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/contract/auth/manager/AuthManager.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/codec/decode/TransactionDecoderInterface.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/codec/decode/TransactionDecoderService.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessor.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessorInterface.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionWithRemoteSignProcessor.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionWithRemoteSignProviderInterface.java
  src/integration-test/java/org/fisco/bcos/sdk/transaction/decoder/EventDecodeTest.java
  src/integration-test/java/org/fisco/bcos/sdk/transaction/manager/AssembleTransactionProcessorTest.java
Labels: v3.x, refactor

#497 Fix: fix the bug of keyPairFactory not use config.
  sdk-crypto/src/main/java/org/fisco/bcos/sdk/crypto/CryptoSuite.java
Labels: bugfix

#498 fix：issues #352
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/ABICodec.java
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/EventEncoder.java
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/FunctionEncoder.java
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/wrapper/ABIDefinition.java
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/wrapper/ABIDefinitionFactory.java
  sdk-abi/src/main/java/org/fisco/bcos/sdk/abi/wrapper/ContractABIDefinition.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/contract/Contract.java
  sdk-transaction/src/main/java/org/fisco/bcos/sdk/transaction/codec/decode/TransactionDecoderService.java
Labels: bugfix
